const COPILOT_CUSTOM = {
  "spf-missing": {
    whatIsWrong: "The domain does not publish an SPF (Sender Policy Framework) record.",
    whyItMatters: "Without SPF, anyone can send emails pretending to come from your domain, making it easy for attackers to execute spoofing and phishing campaigns.",
    howAutoRemediateCanFix: "AutoRemediate can publish a default secure SPF TXT record via your DNS provider.",
    accessNeeded: ["DNS write access"],
    whatCouldBreak: "If you have existing email senders not included in the default record, their emails might get rejected or sent to spam.",
    verificationPlan: "Query the DNS TXT record for the domain and check that 'v=spf1 ...' is returned.",
    rollbackPlan: "Delete or revert the SPF TXT record in your DNS zone."
  },
  "spf-softfail": {
    whatIsWrong: "The SPF record is configured with a soft fail (~all) mechanism.",
    whyItMatters: "A soft fail flags suspicious emails but still allows them to be delivered, which weakens protection against spoofing.",
    howAutoRemediateCanFix: "AutoRemediate can update the SPF record to use a strict hard fail (-all) mechanism.",
    accessNeeded: ["DNS write access"],
    whatCouldBreak: "Legitimate emails sent from unauthorized servers will be completely blocked instead of flagged.",
    verificationPlan: "Check the SPF TXT record to confirm it ends with '-all' instead of '~all'.",
    rollbackPlan: "Revert the SPF TXT record mechanism back to '~all'."
  },
  "dmarc-missing": {
    whatIsWrong: "The domain does not publish a DMARC policy.",
    whyItMatters: "Attackers can spoof email from this domain because receiving mail servers have no instructions on how to handle failed authentication.",
    howAutoRemediateCanFix: "AutoRemediate can create a DMARC TXT record pointing to a policy of quarantine or reject.",
    accessNeeded: ["DNS write access"],
    whatCouldBreak: "A strict DMARC policy may block legitimate emails if your SPF/DKIM configurations are not properly aligned.",
    verificationPlan: "Verify that the _dmarc.TARGET TXT record resolves to the correct policy.",
    rollbackPlan: "Delete or revert the DMARC TXT record."
  },
  "dmarc-none": {
    whatIsWrong: "The DMARC policy is set to p=none (monitoring only).",
    whyItMatters: "A monitoring-only policy does not block or quarantine unauthorized emails, offering no active spoofing protection.",
    howAutoRemediateCanFix: "AutoRemediate can update the DMARC policy from p=none to p=quarantine.",
    accessNeeded: ["DNS write access"],
    whatCouldBreak: "Emails from misconfigured legitimate senders will be sent to the recipient's spam folder.",
    verificationPlan: "Verify the DMARC record contains 'p=quarantine'.",
    rollbackPlan: "Revert the policy back to 'p=none'."
  },
  "dkim-missing": {
    whatIsWrong: "We could not find a DKIM public key record on common selectors.",
    whyItMatters: "Without DKIM signatures, receiving email servers cannot verify if the email was actually sent by your domain and wasn't altered in transit.",
    howAutoRemediateCanFix: "This requires you to provide the DKIM public key and selector generated by your specific email provider.",
    accessNeeded: ["Email provider console access", "DNS write access"],
    whatCouldBreak: "No risk of breakage, as publishing a new DKIM key does not affect existing email flows.",
    verificationPlan: "Check that the [selector]._domainkey.TARGET DNS TXT record resolves and matches your email provider's key.",
    rollbackPlan: "Delete the newly created DKIM TXT record."
  },
  "csp-missing": {
    whatIsWrong: "The Content-Security-Policy (CSP) header is not present in server responses.",
    whyItMatters: "Without CSP, the browser will execute any scripts loaded from any source, exposing users to Cross-Site Scripting (XSS) and data injection.",
    howAutoRemediateCanFix: "AutoRemediate can set a CSP header at the CDN edge using Cloudflare Transform Rules or CloudFront policies.",
    accessNeeded: ["Cloud provider API access or server configuration access"],
    whatCouldBreak: "A strict CSP policy may block legitimate inline scripts or third-party resources if they are not explicitly whitelisted.",
    verificationPlan: "Verify the presence of Content-Security-Policy in response headers via curl or browser developer tools.",
    rollbackPlan: "Disable the Cloudflare Transform Rule or delete the header policy configuration."
  },
  "hsts-missing": {
    whatIsWrong: "The HTTP Strict-Transport-Security (HSTS) header is missing.",
    whyItMatters: "Browsers might connect to your site over insecure HTTP, exposing users to SSL stripping and man-in-the-middle attacks.",
    howAutoRemediateCanFix: "AutoRemediate can set the HSTS response header with max-age=31536000 at the edge provider.",
    accessNeeded: ["Cloud provider API access or server configuration access"],
    whatCouldBreak: "Once HSTS is enabled, browsers will reject all insecure HTTP connections, which will break access if the domain has subdomains that do not support HTTPS.",
    verificationPlan: "Check for Strict-Transport-Security in the HTTP response headers.",
    rollbackPlan: "Remove the HSTS rule or policy (note: browsers cache HSTS, so rollback may not be immediate for returning users)."
  },
  "xframe-missing": {
    whatIsWrong: "The X-Frame-Options header is not configured.",
    whyItMatters: "Malicious sites can frame your application inside an iframe, enabling clickjacking attacks to trick users into performing unintended actions.",
    howAutoRemediateCanFix: "AutoRemediate can add X-Frame-Options: DENY or SAMEORIGIN at the edge/server level.",
    accessNeeded: ["Cloud provider API access or server configuration access"],
    whatCouldBreak: "If your site legitimately needs to be embedded in an iframe on other trusted sites, it will fail to load.",
    verificationPlan: "Verify the X-Frame-Options header is returned in response headers.",
    rollbackPlan: "Remove or disable the X-Frame-Options response header rule."
  },
  "xcto-missing": {
    whatIsWrong: "The X-Content-Type-Options header is missing.",
    whyItMatters: "Without it, browsers might MIME-sniff response content, potentially executing user-uploaded files as scripts (MIME-sniffing vulnerabilities).",
    howAutoRemediateCanFix: "AutoRemediate can inject X-Content-Type-Options: nosniff into response headers.",
    accessNeeded: ["Cloud provider API access or server configuration access"],
    whatCouldBreak: "Legacy client browsers might fail to load files with mismatched MIME types.",
    verificationPlan: "Verify that the X-Content-Type-Options header is present and set to 'nosniff'.",
    rollbackPlan: "Disable or remove the header rule."
  },
  "server-version-exposed": {
    whatIsWrong: "The server response headers disclose detailed operating system or application server version information.",
    whyItMatters: "Exposed server banners help attackers identify known CVE vulnerabilities for your specific server version.",
    howAutoRemediateCanFix: "This requires applying a server configuration patch (e.g. ServerTokens Prod in Apache, server_tokens off in Nginx).",
    accessNeeded: ["SSH server root configuration access"],
    whatCouldBreak: "No risk of breakage; it only suppresses diagnostic version banners.",
    verificationPlan: "Inspect the Server header in HTTP responses to verify version numbers are hidden.",
    rollbackPlan: "Revert the server configuration file changes and restart the web server."
  },
  "xpoweredby-exposed": {
    whatIsWrong: "The response headers contain the X-Powered-By header, revealing the backend application framework or runtime version.",
    whyItMatters: "Banners detailing runtime frameworks (e.g. PHP/8.1) allow attackers to lookup and target version-specific vulnerabilities.",
    howAutoRemediateCanFix: "This requires editing backend runtime configs (like php.ini expose_php = Off) or strip headers via CDN edge.",
    accessNeeded: ["SSH configuration access or Cloud provider API access"],
    whatCouldBreak: "No operational impact; the header is purely diagnostic.",
    verificationPlan: "Verify the X-Powered-By header is completely absent from response headers.",
    rollbackPlan: "Revert framework/webserver rules stripping the header."
  },
  "cookie-insecure": {
    whatIsWrong: "Sensitive session cookies are transmitted without HttpOnly, Secure, or SameSite attributes.",
    whyItMatters: "Without HttpOnly, malicious scripts can steal session cookies via XSS. Without Secure, cookies are transmitted over unencrypted HTTP, exposing them to interception.",
    howAutoRemediateCanFix: "This requires updating your application configuration (like session middleware or php.ini) to include security flags.",
    accessNeeded: ["Application codebase/server configuration access"],
    whatCouldBreak: "Cookies might not be sent in cross-site requests if SameSite=Strict is set, affecting login integrations.",
    verificationPlan: "Inspect Set-Cookie headers in the response and check for Secure, HttpOnly, and SameSite fields.",
    rollbackPlan: "Remove the cookie security directives from configuration files."
  },
  "error-disclosure": {
    whatIsWrong: "The server displays detailed stack traces, raw error descriptions, or database exceptions to the client.",
    whyItMatters: "Diagnostic leaks reveal file structure, database tables, and library versions, helping attackers plan automated exploitation.",
    howAutoRemediateCanFix: "This requires modifying application code or web server settings to log errors internally and display generic error pages.",
    accessNeeded: ["Web server or codebase configuration access"],
    whatCouldBreak: "Developers will have to review server log files instead of viewing errors in the browser.",
    verificationPlan: "Attempt a page request that triggers an error and confirm that no stack traces are shown.",
    rollbackPlan: "Revert error logging configurations back to display errors."
  },
  "stale-txt-token": {
    whatIsWrong: "The domain publishes old domain verification or API TXT records (e.g., legacy Google or loader.io tokens).",
    whyItMatters: "Stale validation records disclose historical tools and services you used, creating footprinting opportunities for attackers.",
    howAutoRemediateCanFix: "AutoRemediate can delete these stale TXT records from your DNS provider.",
    accessNeeded: ["DNS write access"],
    whatCouldBreak: "If the associated services are actually still in use, they might lose domain verification.",
    verificationPlan: "Query your domain's TXT records to confirm the stale token record has been removed.",
    rollbackPlan: "Recreate the deleted TXT record in your DNS dashboard."
  },
  "subdomain-takeover": {
    whatIsWrong: "A subdomain points to a third-party service (e.g. S3, CloudFront) that has been deleted or is unclaimed.",
    whyItMatters: "Attackers can register a resource under the same name on the third-party provider and hijack your subdomain to serve malicious content or steal cookies.",
    howAutoRemediateCanFix: "AutoRemediate can remove the dangling CNAME record from your DNS provider.",
    accessNeeded: ["DNS write access"],
    whatCouldBreak: "If the third-party resource was actually valid, the service will stop resolving.",
    verificationPlan: "Verify the subdomain CNAME DNS query no longer resolves.",
    rollbackPlan: "Re-add the deleted CNAME DNS record."
  }
};

// "Operational risk" = the chance that APPLYING the fix breaks something in
// production. That is deliberately NOT the vulnerability's severity, and the
// two are independent — sometimes inverse. Hiding a `Server:` version banner
// is a HIGH-severity finding with essentially zero deployment risk; enabling
// HSTS is only MODERATE severity but its rollback is capped by a one-year
// browser cache.
//
// The old code set riskLevel from finding.severity, so the field just restated
// the severity badge shown directly above it, and every PASS finding was
// hardcoded "low" — which is what made the drawer look like it always says LOW
// (PASS findings are usually the majority of a scan).
//
// Scored on blast radius + reversibility, and kept consistent with the
// whatCouldBreak / rollbackPlan prose in COPILOT_CUSTOM above.
const FIX_RISK = {
  // --- High: can break mail delivery or page rendering, or is slow to undo ---
  "hsts-missing": {
    level: "high",
    basis: "Forces HTTPS across the domain and any subdomains. Browsers cache the max-age (1 year), so an incorrect rollout cannot be quickly reversed for visitors who already received the header."
  },
  "csp-missing": {
    level: "high",
    basis: "A policy that misses a legitimate script, style, or third-party origin will block it outright. CSP is the most common cause of breakage among header fixes."
  },
  "spf-missing": {
    level: "high",
    basis: "Publishing -all rejects mail from any sender not listed. Missing a legitimate sender (marketing tool, ticketing system, CRM) causes their mail to bounce."
  },
  "spf-softfail": {
    level: "high",
    basis: "Tightening ~all to -all converts 'flag as suspicious' into 'reject'. Any unlisted legitimate sender starts bouncing immediately."
  },
  "dmarc-missing": {
    level: "high",
    basis: "A quarantine policy sends unaligned mail to spam. If SPF/DKIM alignment is incomplete, legitimate mail is affected as soon as the record propagates."
  },
  "dmarc-none": {
    level: "high",
    basis: "Moving from monitoring to quarantine starts acting on failures that were previously only reported. Review your DMARC aggregate reports first."
  },
  "subdomain-takeover": {
    level: "high",
    basis: "Deleting the CNAME takes the subdomain offline if the target was actually still in use. Confirm the resource is genuinely unclaimed at the provider before applying — the detection signal alone does not prove it."
  },

  // --- Medium: narrower blast radius, straightforward to undo ---
  "xframe-missing": {
    level: "medium",
    basis: "Blocks framing of the site. Breaks any legitimate embedding in partner sites, dashboards, or internal tools. Reversible by removing the header."
  },
  "cookie-insecure": {
    level: "medium",
    basis: "SameSite=Strict can break cross-site sign-in flows and payment redirects that rely on cookies surviving a third-party hop."
  },
  "stale-txt-token": {
    level: "medium",
    basis: "If the associated service is still active, deleting the token revokes its domain verification. Reversible by re-adding the record."
  },

  // --- Low: no functional change to the application ---
  "xcto-missing": {
    level: "low",
    basis: "nosniff only stops MIME-type guessing. Affects legacy browsers serving files with mismatched Content-Type."
  },
  "referrer-missing": {
    level: "low",
    basis: "Reduces referrer detail sent to third parties. May affect analytics attribution; no functional impact on the site."
  },
  "permissions-missing": {
    level: "low",
    basis: "Restricts browser feature access (camera, geolocation, etc.). Only affects features the site actually requests."
  },
  "server-version-exposed": {
    level: "low",
    basis: "Suppresses a diagnostic banner. No functional change to request handling."
  },
  "xpoweredby-exposed": {
    level: "low",
    basis: "Removes a purely informational header. No operational impact."
  },
  "error-disclosure": {
    level: "low",
    basis: "Errors are written to server logs instead of the browser. Developers lose in-browser tracebacks but behaviour is unchanged."
  },
  "dkim-missing": {
    level: "low",
    basis: "Publishing a DKIM key is additive — existing mail flow is unaffected until the provider begins signing with it."
  }
};

// Fallback by fix mechanism when a finding id has no explicit entry.
const FIX_TYPE_RISK = {
  "dns": {
    level: "medium",
    basis: "Adds a DNS record. Effects appear as caches expire and are reversed by deleting the record."
  },
  "dns-update": {
    level: "medium",
    basis: "Modifies an existing DNS record. Keep the previous value so it can be restored if the change causes problems."
  },
  "dns-delete": {
    level: "medium",
    basis: "Removes a DNS record. Disruptive if the record is still relied upon; reversible by re-creating it."
  },
  "cloudflare-rule": {
    level: "medium",
    basis: "Injects a response header at the edge for every request. Reversible by disabling the rule."
  },
  "config": {
    level: "medium",
    basis: "Requires a server configuration change and a service reload. Stage it before applying in production."
  }
};

function computeFixRisk(finding) {
  // Nothing is being applied for a passing check, so there is no operational
  // risk to report. Returning null lets the UI omit the row entirely rather
  // than print a meaningless "LOW".
  if (finding.status === "PASS") {
    return { level: null, basis: null };
  }

  const byId = FIX_RISK[finding.id];
  if (byId) return byId;

  if (finding.fix && FIX_TYPE_RISK[finding.fix.type]) {
    return FIX_TYPE_RISK[finding.fix.type];
  }

  return {
    level: "medium",
    basis: "No risk assessment is recorded for this fix. Review the change manually before applying it."
  };
}

function buildRemediation(finding) {
  const risk = computeFixRisk(finding);
  const isTerraformable = ['csp-missing', 'csp', 'hsts-missing', 'hsts', 'xframe-missing', 'xframe', 'xcto-missing', 'xcto', 'spf-missing', 'spf-softfail', 'spf', 'dmarc-missing', 'dmarc-none', 'dmarc', 'subdomain-takeover', 'subdomain-takeover-clean', 'stale-txt-token', 'stale-txt'].includes(finding.id) || !!finding.fix;

  if (finding.status === "PASS") {
    return {
      readiness: "verified",
      label: "Verified",
      primaryAction: "Close",
      secondaryAction: isTerraformable ? "Export Terraform" : null,
      riskLevel: risk.level,
      riskBasis: risk.basis,
      provider: ["cloudflare", "aws"],
      requires: [],
      canAutoFix: false,
      canExportTerraform: isTerraformable,
      canRollback: false
    };
  }

  if (finding.id === "dkim-missing") {
    return {
      readiness: "needs_input",
      label: "Needs DKIM value",
      primaryAction: "Provide Details",
      secondaryAction: "View Guide",
      riskLevel: risk.level,
      riskBasis: risk.basis,
      provider: ["cloudflare", "aws", "manual"],
      requires: ["Mail provider DKIM selector", "DKIM public key"],
      canAutoFix: false,
      canExportTerraform: false,
      canRollback: false
    };
  }

  if (finding.fix) {
    if (finding.fix.type === "dns" || finding.fix.type === "dns-update" || finding.fix.type === "cloudflare-rule") {
      return {
        readiness: "auto_fixable",
        label: "Auto-fixable",
        primaryAction: "Auto-Fix",
        secondaryAction: "Export Terraform",
        riskLevel: risk.level,
        riskBasis: risk.basis,
        provider: ["cloudflare", "aws"],
        requires: ["Cloudflare API token or AWS connection"],
        canAutoFix: true,
        canExportTerraform: true,
        canRollback: true
      };
    }

    if (finding.fix.type === "dns-delete") {
      return {
        readiness: "auto_fixable",
        label: "Auto-fixable",
        primaryAction: "Auto-Fix",
        secondaryAction: "Export Terraform",
        riskLevel: risk.level,
        riskBasis: risk.basis,
        provider: ["cloudflare", "aws"],
        requires: ["DNS write access"],
        canAutoFix: true,
        canExportTerraform: true, // We will output comment-only removal instructions
        canRollback: true
      };
    }

    if (finding.fix.type === "config") {
      return {
        readiness: "generate_patch",
        label: "Generate patch",
        primaryAction: "Generate Patch",
        secondaryAction: "View Fix",
        riskLevel: risk.level,
        riskBasis: risk.basis,
        provider: ["apache", "nginx"],
        requires: ["Server config access"],
        canAutoFix: false,
        canExportTerraform: false,
        canRollback: false
      };
    }
  }

  return {
    readiness: "manual",
    label: "Manual Fix",
    primaryAction: "View Fix",
    secondaryAction: "View Guide",
    riskLevel: risk.level,
    riskBasis: risk.basis,
    provider: ["manual"],
    requires: ["Administrator access"],
    canAutoFix: false,
    canExportTerraform: false,
    canRollback: false
  };
}

function buildCopilot(finding, target) {
  const custom = COPILOT_CUSTOM[finding.id];
  const template = custom ? { ...custom } : {
    whatIsWrong: finding.description || "No vulnerability details available.",
    whyItMatters: "This misconfiguration may expose your site infrastructure to potential attacks.",
    howAutoRemediateCanFix: finding.fix ? "AutoRemediate can resolve this configuration by updating DNS or CDN settings." : "Manual server configuration changes are required.",
    accessNeeded: finding.fix ? ["Connected cloud provider token"] : ["Administrator server access"],
    whatCouldBreak: "Ensure to review configuration patches before deploying in production settings.",
    verificationPlan: "Re-run a target security scan to ensure the finding is marked as PASS.",
    rollbackPlan: "Revert the applied configuration change manually or through your CDN console."
  };

  template.exactChange = finding.fix || null;
  
  // Format variables like TARGET/example.com in template strings
  const formatText = (text) => {
    if (!text) return "";
    return text.replace(/TARGET/g, target).replace(/example\.com/g, target);
  };

  return {
    whatIsWrong: formatText(template.whatIsWrong),
    whyItMatters: formatText(template.whyItMatters),
    howAutoRemediateCanFix: formatText(template.howAutoRemediateCanFix),
    accessNeeded: template.accessNeeded || [],
    exactChange: template.exactChange,
    whatCouldBreak: formatText(template.whatCouldBreak),
    verificationPlan: formatText(template.verificationPlan),
    rollbackPlan: formatText(template.rollbackPlan)
  };
}

function applyRemediationMetadata(findings, target) {
  return findings.map(finding => ({
    ...finding,
    remediation: buildRemediation(finding),
    copilot: buildCopilot(finding, target)
  }));
}

module.exports = { applyRemediationMetadata, buildRemediation, buildCopilot, computeFixRisk };
